query = select from';'
_ = ' '
select = #' *select *'  [col-name {',' col-name}]
col-name = keyword | string | star

keyword = #' *:[0-9\w-]* *'
string = #' *[0-9\w-]* *'
star = #' *\* *'
number = #' *[0-9]+ *'

from = #' *from *' table-name
table-name = keyword | string

(*
select = 'select'
clj-map-key = number | keyword | string
query = select [_] [col-name {_} {',' {_} col-name}] {_} from {_} table-name {_} ';'
*)
